name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Generate MSIX Installer
        run: flutter pub run msix:create --display-name "Smart Inverter" --publisher-display-name "Yura Antonov" --msix-version 1.1.0.0

      - name: Package Release Files
        run: |
          $version = "${{ github.ref_name }}"
          if ($version -eq "main") { $version = "latest" }
          
          # Prepare ZIP
          mkdir release_zip
          copy-item -Path "build\windows\x64\runner\Release\*" -Destination "release_zip" -Recurse
          compress-archive -Path "release_zip\*" -DestinationPath "smart_inverter_windows_$version.zip"
          
          # Move MSIX
          move-item -Path "build\windows\x64\runner\Release\*.msix" -Destination "smart_inverter_installer_$version.msix"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            smart_inverter_windows_${{ github.ref_name }}.zip
            smart_inverter_installer_${{ github.ref_name }}.msix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
